import { OnInit, TemplateRef, EventEmitter, AfterViewInit, ElementRef, OnChanges } from '@angular/core';
import { WidgetActionType } from '../core/enums/widget-action-type.enum';
export declare class CmacsKpiGroupComponent implements OnInit, AfterViewInit, OnChanges {
    columnTemplate: TemplateRef<{}>;
    canvasRef: ElementRef;
    clickMenu: EventEmitter<any>;
    headerText: string;
    footerText: string;
    footerValue: string;
    view: number[];
    data: any[];
    columnsHeader: string[];
    chartWidth: number;
    fontChartNumber: number;
    col2: number;
    col3: number;
    minWidth: number;
    showChart: boolean;
    scrollY: number;
    p: number;
    scroll: {
        x: string;
        y: string;
    };
    dataTable: any[];
    configurationExpandableRows: any;
    loading: boolean;
    selectedItem: string;
    constructor();
    ngOnInit(): void;
    ngOnChanges(): void;
    ngAfterViewInit(): void;
    setScroll(): void;
    drawCanvas(): void;
    drawPieSlice(ctx: CanvasRenderingContext2D, centerX: number, centerY: number, radius: number, startAngle: number, endAngle: number, color: any, lineWidth: number): void;
    getTotalCateg(data: any[]): number;
    setConfiguration(): void;
    setData(): void;
    getChildren(items: any[]): any[];
    menuClick(type: WidgetActionType): void;
    changeData(key: string): void;
}
