import { EventEmitter, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { SignaturePad } from 'angular2-signaturepad/signature-pad';
import { UploadFile } from "ng-zorro-antd";
export declare const SIGNATURE_LOCALIZATION: {
    'Click here to sign': string;
    'Sign to Complete': string;
    'Cancel': string;
    'Verify': string;
    'Enter Your Name': string;
    'Text Here': string;
    'Type': string;
    'Draw': string;
    'Image': string;
    'I, User Full Name, have reviewed and completed this report.': string;
    'Select here to save your signature for future use.': string;
    'Signature': string;
    'Drag & Drop File Here or': string;
    'Browse Computer': string;
};
export declare class CmacsSignatureComponent {
    private fb;
    private cdr;
    _isVisible: boolean;
    formGroup: FormGroup;
    saveSignature: boolean;
    _i18n: {
        'Click here to sign': string;
        'Sign to Complete': string;
        'Cancel': string;
        'Verify': string;
        'Enter Your Name': string;
        'Text Here': string;
        'Type': string;
        'Draw': string;
        'Image': string;
        'I, User Full Name, have reviewed and completed this report.': string;
        'Select here to save your signature for future use.': string;
        'Signature': string;
        'Drag & Drop File Here or': string;
        'Browse Computer': string;
    };
    current: number;
    files: any[];
    _signatureDataUrl: any;
    _currentValue: any;
    _signaturePadOptions: Object;
    _uploadedImageSrc: any;
    _uploadedImageSrcStyle: any;
    i18n: any;
    signaturePadOptions: Object;
    extendedVersion: boolean;
    oncancel: EventEmitter<boolean>;
    onsubmit: EventEmitter<any>;
    signaturePad: SignaturePad;
    ondrawend: EventEmitter<any>;
    currentValue: any;
    constructor(fb: FormBuilder, cdr: ChangeDetectorRef);
    ngAfterViewInit(): void;
    onResizeStop($event: any): void;
    onMoveEnd($event: any): void;
    beforeUpload: (file: UploadFile) => boolean;
    private extname;
    isValid(): boolean;
    updateCurrent(idx: any): void;
    drawComplete(): void;
    openModal(): void;
    handleCancel(): void;
    handleOk(): void;
    checkPressedKeys($event: any): void;
}
