import { ChangeDetectorRef, ElementRef, EventEmitter, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { CmacsCardTabComponent } from './cmacs-card-tab.component';
export declare type CmacsCardType = 'file' | 'selection' | 'action' | 'team' | 'project' | 'folder' | 'measure' | 'none';
export declare class CmacsCardComponent implements OnInit {
    private cdr;
    folderIcon: string;
    isEditable: boolean;
    bordered: boolean;
    opened: boolean;
    editable: boolean;
    isRadio: boolean;
    loading: boolean;
    disabled: boolean;
    hoverable: boolean;
    bodyStyle: {
        [key: string]: string;
    };
    cover: TemplateRef<void>;
    body: TemplateRef<void>;
    actions: Array<TemplateRef<void>>;
    team: any;
    project: any;
    type: string;
    cmacsType: CmacsCardType;
    cmacsIcon: string;
    title: string | TemplateRef<void>;
    titleChange: EventEmitter<string>;
    extra: string | TemplateRef<void>;
    tab: CmacsCardTabComponent;
    open: EventEmitter<any>;
    close: EventEmitter<any>;
    selected: boolean;
    value: any;
    selectedChange: EventEmitter<boolean>;
    constructor(cdr: ChangeDetectorRef, renderer: Renderer2, elementRef: ElementRef);
    ngOnInit(): void;
    onClick(event: Event): void;
    onDblClick(): void;
    markForCheck(): void;
    select(event: Event): void;
    handleEnter(event: KeyboardEvent, titleContainer: any, titleSpan: any): void;
    toggleEdit(titleContainer: any): void;
    getInitials(name: any): any;
}
