import { CdkConnectedOverlay, ConnectedOverlayPositionChange } from '@angular/cdk/overlay';
import { Platform } from '@angular/cdk/platform';
import { AfterContentInit, ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, QueryList, SimpleChanges } from '@angular/core';
import { NzMenuBaseService, NzNoAnimationDirective, NzUpdateHostClassService } from 'ng-zorro-antd/core';
import { CmacsMenuItemDirective } from './cmacs-menu-item.directive';
import { CmacsSubmenuService } from './cmacs-submenu.service';
export declare class CmacsSubMenuComponent implements OnInit, OnDestroy, AfterContentInit, OnChanges {
    private elementRef;
    menuService: NzMenuBaseService;
    private cdr;
    submenuService: CmacsSubmenuService;
    private updateHostClassService;
    private platform;
    noAnimation?: NzNoAnimationDirective;
    menuClassName: string;
    paddingLeft: number;
    open: boolean;
    disabled: boolean;
    readonly openChange: EventEmitter<boolean>;
    cdkConnectedOverlay: CdkConnectedOverlay;
    cdkOverlayOrigin: ElementRef;
    listOfCmacsSubMenuComponent: QueryList<CmacsSubMenuComponent>;
    listOfCmacsMenuItemDirective: QueryList<CmacsMenuItemDirective>;
    placement: string;
    triggerWidth: number;
    expandState: string;
    overlayPositions: import("@angular/cdk/overlay").ConnectionPositionPair[];
    private destroy$;
    private isChildMenuSelected;
    private isMouseHover;
    setOpenState(open: boolean): void;
    clickSubMenuTitle(): void;
    setMouseEnterState(value: boolean): void;
    setTriggerWidth(): void;
    onPositionChange(position: ConnectedOverlayPositionChange): void;
    setClassMap(): void;
    constructor(elementRef: ElementRef, menuService: NzMenuBaseService, cdr: ChangeDetectorRef, submenuService: CmacsSubmenuService, updateHostClassService: NzUpdateHostClassService, platform: Platform, noAnimation?: NzNoAnimationDirective);
    ngOnInit(): void;
    ngAfterContentInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
}
